security:
    providers:
        in_memory: { memory: ~ }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#         secured_area:
#             anonymous: ~
#             pattern: ^/(enseignant|etudiant)
# #            http_basic: ~
#             stateless: true
#             simple_preauth:
#                 authenticator: App\Security\ApiKeyAuthenticator
#             provider: api_key_user_provider
#             logout:
#                 path:   logout
#                 target: home
#             form_login:
#                 login_path: home
#                 check_path: home

        main:
            anonymous: ~
            pattern: ^/
            stateless: true

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_ADMIN }

