twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']    
    globals:
        pusherKey: '%env(PUSHER_KEY)'
        pusherCluster: '%env(PUSHER_CLUSTER)%'
#    exception_controller: App\Controller\CustomExceptionController::showAction