<?php
namespace App\Controller;


use Symfony\Bundle\TwigBundle\Controller\ExceptionController;
use Symfony\Component\Debug\Exception\FlattenException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Log\DebugLoggerInterface;
use Twig\Environment;

class CustomExceptionController extends ExceptionController
{
    public function __construct(Environment $twig, bool $debug)
    {
        parent::__construct($twig, $debug);
    }

    public function showAction(Request $request, FlattenException $exception, DebugLoggerInterface $logger = null)
    {
//        if ($exception->getStatusCode() === 404){
//            return $this->findTemplate($request, 'twig', 404, );
//        }
        return parent::showAction($request, $exception, $logger); // TODO: Change the autogenerated stub
    }

    protected function getAndCleanOutputBuffering($startObLevel)
    {
        return parent::getAndCleanOutputBuffering($startObLevel); // TODO: Change the autogenerated stub
    }

    protected function findTemplate(Request $request, $format, $code, $showException)
    {
        return parent::findTemplate($request, $format, $code, $showException); // TODO: Change the autogenerated stub
    }

    protected function templateExists($template)
    {
        return parent::templateExists($template); // TODO: Change the autogenerated stub
    }
}